### Chapter 1: Linear Algebra

#### 1. Vector Addition
$$ u = [x_1, y_1] $$  
$$ v = [x_2, y_2] $$
$$ u+v = [x_1 + x_2, y_1 + y_2] $$ 


In [1]:
import numpy as np
u = np.array([1,2])
v = np.array([3,4])
result = u + v
print(result)

[4 6]


#### 2. Scalar Multiplication of a vector
$$ \alpha = 3\ $$ 
$$ u = [x_1, y_1] $$
$$ v =  \alpha * u $$

In [2]:
import numpy as np
alpha = 3
u = np.array([3, -1])
result = alpha * u
print(result)

[ 9 -3]


### 3. Dot product
$$ u . v = \Sigma_{i=1}^{n} u_i*v_i = u_1v_1 + u_2v_2 + u_3v_3 +........+ u_nv_ni $$

In [ ]:
import numpy as np
u = np.array([1, 2])
v = np.array([3, 4])
result = np.dot(u, v)
print(result)

11


#### 4. Cross Product (3D)
$$ u = [u_1, u_2, u_3] $$  
$$ v = [v_1, v_2, v_3] $$
$$ u \times v = \begin{vmatrix}
i & j & k\\
u_1 & u_2 & u_3\\
v_1 & v_2 & v_3 
\end{vmatrix} $$

In [4]:
import numpy as np
u = np.array([1, 0, 0])
v = np.array([0, 1, 0])
result = np.cross(u, v)
print(result)

[0 0 1]


#### 5. Norm of vector (Euclidean)
$$ ||v|| = \sqrt{\Sigma_{i=1}^{n}v_i^2} = \sqrt{v_1^2 + v_2^2 + ..... + v_n^2   } $$

In [6]:
import numpy as np
v = np.array([3, 4])
result = np.linalg.norm(v)
print(result)

5.0


#### 6. Orthogonality Condition
$$ u.v = 0 $$

In [ ]:
import numpy as np
u = np.array([1, 2])
v = np.array([2, -1])
result = np.dot(u, v)
print(result)

0


#### 7. Matrix Addition
$$ A + B = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & a_{22}\end{bmatrix} +  \begin{bmatrix} b_{11} & b_{12}\\ b_{21} & b_{22}\end{bmatrix} = \begin{bmatrix} a_{11} + b_{11}& a_{12} + b_{12}\\ a_{12} + b_{21} & a_{22} + b_{22}\end{bmatrix} $$

In [9]:
import numpy as np
A = np.array([[1, 2,], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result =  A + B
print(result)

[[ 6  8]
 [10 12]]


#### 8. Matrix Scalar Multiplication
$$ \alpha * A = \alpha \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} \alpha a_{11} & \alpha a_{12}\\ \alpha a_{21} & \alpha b_{22} \end{bmatrix}$$

In [11]:
import numpy as np
alpha = 2
A = np.array([[1, 2], [3, 4]])
result = alpha * A
print(result)

[[2 4]
 [6 8]]


#### 9. Matrix - Vector Multiplication
$$ Ax = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & b_{22} \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} a_{11}x_1 & a_{12}x_2\\ a_{21}x_1 & b_{22}x_2 \end{bmatrix}$$

In [14]:
import numpy as np
A = np.array([[1, 2], [3, 4]]) 
x = np.array([5, 6])
result = np.dot(A, x)
print(result)

[17 39]


#### 10. Matrix Multiplication
$$ C = AB, c_{ij} = \Sigma_{k=1}^{n}a_{ik}b_{kj} $$

In [21]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result1 = np.matmul(A, B)
result2 = np.dot(A, B)
print(result1, "\n\n", result2)


[[19 22]
 [43 50]] 

 [[19 22]
 [43 50]]


#### 11. Transpose of a Matrix
$$ A^T = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & b_{22} \end{bmatrix}^T = \begin{bmatrix} a_{11} & a_{21}\\ a_{12} & b_{22} \end{bmatrix} $$

In [23]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result1= np.transpose(A)
result2 = A.T
print(result1, "\n\n", result2)

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

 [[1 4 7]
 [2 5 8]
 [3 6 9]]
