### Chapter 1: Linear Algebra

#### 1. Vector Addition
$$ u = [x_1, y_1] $$  
$$ v = [x_2, y_2] $$
$$ u+v = [x_1 + x_2, y_1 + y_2] $$ 


In [1]:
import numpy as np
u = np.array([1,2])
v = np.array([3,4])
result = u + v
print(result)

[4 6]


#### 2. Scalar Multiplication of a vector
$$ \alpha = 3\ $$ 
$$ u = [x_1, y_1] $$
$$ v =  \alpha * u $$

In [2]:
import numpy as np
alpha = 3
u = np.array([3, -1])
result = alpha * u
print(result)

[ 9 -3]


### 3. Dot product
$$ u . v = \Sigma_{i=1}^{n} u_i*v_i = u_1v_1 + u_2v_2 + u_3v_3 +........+ u_nv_ni $$

In [ ]:
import numpy as np
u = np.array([1, 2])
v = np.array([3, 4])
result = np.dot(u, v)
print(result)

11


#### 4. Cross Product (3D)
$$ u = [u_1, u_2, u_3] $$  
$$ v = [v_1, v_2, v_3] $$
$$ u \times v = \begin{vmatrix}
i & j & k\\
u_1 & u_2 & u_3\\
v_1 & v_2 & v_3 
\end{vmatrix} $$

In [4]:
import numpy as np
u = np.array([1, 0, 0])
v = np.array([0, 1, 0])
result = np.cross(u, v)
print(result)

[0 0 1]


#### 5. Norm of vector (Euclidean)
$$ ||v|| = \sqrt{\Sigma_{i=1}^{n}v_i^2} = \sqrt{v_1^2 + v_2^2 + ..... + v_n^2   } $$

In [6]:
import numpy as np
v = np.array([3, 4])
result = np.linalg.norm(v)
print(result)

5.0


#### 6. Orthogonality Condition
$$ u.v = 0 $$

In [ ]:
import numpy as np
u = np.array([1, 2])
v = np.array([2, -1])
result = np.dot(u, v)
print(result)

0


#### 7. Matrix Addition
$$ A + B = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & a_{22}\end{bmatrix} +  \begin{bmatrix} b_{11} & b_{12}\\ b_{21} & b_{22}\end{bmatrix} = \begin{bmatrix} a_{11} + b_{11}& a_{12} + b_{12}\\ a_{12} + b_{21} & a_{22} + b_{22}\end{bmatrix} $$

In [9]:
import numpy as np
A = np.array([[1, 2,], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result =  A + B
print(result)

[[ 6  8]
 [10 12]]


#### 8. Matrix Scalar Multiplication
$$ \alpha * A = \alpha \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} \alpha a_{11} & \alpha a_{12}\\ \alpha a_{21} & \alpha b_{22} \end{bmatrix}$$

In [11]:
import numpy as np
alpha = 2
A = np.array([[1, 2], [3, 4]])
result = alpha * A
print(result)

[[2 4]
 [6 8]]


#### 9. Matrix - Vector Multiplication
$$ Ax = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & b_{22} \end{bmatrix} \begin{bmatrix} x_{1} \\ x_{2} \end{bmatrix} = \begin{bmatrix} a_{11}x_1 & a_{12}x_2\\ a_{21}x_1 & b_{22}x_2 \end{bmatrix}$$

In [14]:
import numpy as np
A = np.array([[1, 2], [3, 4]]) 
x = np.array([5, 6])
result = np.dot(A, x)
print(result)

[17 39]


#### 10. Matrix Multiplication
$$ C = AB, c_{ij} = \Sigma_{k=1}^{n}a_{ik}b_{kj} $$

In [21]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result1 = np.matmul(A, B)
result2 = np.dot(A, B)
print(result1, "\n\n", result2)


[[19 22]
 [43 50]] 

 [[19 22]
 [43 50]]


#### 11. Transpose of a Matrix
$$ A^T = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & b_{22} \end{bmatrix}^T = \begin{bmatrix} a_{11} & a_{21}\\ a_{12} & b_{22} \end{bmatrix} $$

In [23]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result1= np.transpose(A)
result2 = A.T
print(result1, "\n\n", result2)

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

 [[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 12. Determinant of a 2X2 matrix
$$ det(A) = \begin{vmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{vmatrix} = a_{11}a_{22} + a_{12}a_{21} $$ 

In [24]:
import numpy as np
A = np.array([[3, 8], [4, 6]])
result = np.linalg.det(A)
print(result)

-14.000000000000004


#### 13. Inverse of a 2X2 matrix
$$  A = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & b_{22} \end{bmatrix} $$
$$ A^{-1} = \frac{1}{det(A)} \begin{bmatrix} a_{22} & -a_{12} \\ -a_{12} & a_{11} \end{bmatrix}, det(A) \ne 0 $$

In [25]:
import numpy as np
A = np.array([[3, 8], [4, 6]])
result = np.linalg.inv(A)
print(result)

[[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]


#### 14. Cramer's Rule
$$ Ax = b $$ 
$$ x_i = \frac{det(A_i)}{det(A)}, det(A) \ne 0 $$
$$ A_i \text{ is matrix replaced by each column by $ b $ one by one.} $$


In [59]:
import numpy as np
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])
det_A = np.linalg.det(A)
## solution 1
for i in range(A.shape[1]):
  A_ = A.copy()
  A_[:, i] = b
  x = np.linalg.det(A_)/det_A

## solution 2
x = [np.linalg.det(np.column_stack([b if i == j else A[:, j] for j in range(A.shape[1])])) / det_A for i in range(A.shape[1])]
print(x)

[1.5999999999999994, 1.8]


#### 15. Inverse of a Square matrix
$$ A^{-1} = \frac{1}{det(A)}adj(A), det(A) \ne 0 $$

In [1]:
import numpy as np
A = np.array([[4, 7], [2, 6]])
result = np.linalg.inv(A)
print(result)

[[ 0.6 -0.7]
 [-0.2  0.4]]


#### 16. Determinant of a Triangular Matrix
$$ det(A) = \prod_{i=1}^{n}a_i $$

In [2]:
import numpy as np
A = np.array([[2, 1, 0], [0, 3, 4], [0, 0, 5]])
result = np.prod(np.diag(A))
print(result)

30


#### 17. Rank - Nullity Theorem
$$ rank(A) + nullity(A) = n $$
 $$ n \text{ is number of rows in square matrix} $$

In [3]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rank = np.linalg.matrix_rank(A)
nullity = A.shape[1] - rank 

print(f"rank : {rank}, nullity : {nullity}")

rank : 2, nullity : 1


#### Hadamard (ElementWise) Product
$$ C = A \circ B = \begin{bmatrix} a_{11}b_{11} & a_{12}b_{12} \\ a_{21}b_{21} & a_{22}b_{22}\end{bmatrix} $$

In [4]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.multiply(A, B)
print(result)

[[ 5 12]
 [21 32]]
